docs/price.md, pallets/pallet-tft-price/src/lib.rs
This PR includes
- Rework average price setting
- Update documentation
=> chore: rework avg price setting and docs

pallets/pallet-tfgrid/src/lib.rs, pallets/pallet-tfgrid/src/tests.rs
=> feat: add farm name validation

pallets/pallet-tfgrid/src/lib.rs, pallets/pallet-tfgrid/src/tests.rs, pallets/pallet-tfgrid/src/types.rs
An extra structure used by the node to store some more information about the node object.
=> Node Extra info

pallets/pallet-smart-contract/flowchart.md, pallets/pallet-smart-contract/src/lib.rs, pallets/pallet-smart-contract/src/migration.rs, pallets/pallet-smart-contract/src/tests.rs, pallets/pallet-smart-contract/src/types.rs
Also cleans up contractBillingInfo when contract is canceled
=> fix: dont exclude contracts from billing

pallets/pallet-smart-contract/src/lib.rs, pallets/pallet-smart-contract/src/tests.rs
=> fix(pallet-smart-contract): remove contracts in state delete from billing cycle

substrate-node/pallets/pallet-smart-contract/src/lib.rs
Also disables contract updates for graced contracts
=> fix: update internal lock for graced contracts

substrate-node/pallets/pallet-smart-contract/src/lib.rs, substrate-node/pallets/pallet-smart-contract/src/tests.rs
https://github.com/threefoldtech/tfchain/issues/329
=> feat: rework contract lock

substrate-node/pallets/pallet-smart-contract/src/lib.rs, substrate-node/pallets/pallet-smart-contract/src/tests.rs
https://github.com/threefoldtech/tfchain/issues/326
=> feat: allow creating a rent contract when node is empty

substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/tests.rs
[Removing a Farm is a dangerous operation](https://github.com/threefoldtech/tfchain/issues/359)
=> feat: deprecate remove farm

substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/tests.rs
=> feat: updating ZOS over the chain

substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/tests.rs
=> fix: validate farming policy limits end when attached to farm

substrate-node/pallets/pallet-burning/src/lib.rs, substrate-node/pallets/pallet-dao/src/mock.rs, substrate-node/pallets/pallet-dao/src/tests.rs, substrate-node/pallets/pallet-kvstore/src/lib.rs, substrate-node/pallets/pallet-runtime-upgrade/src/lib.rs, substrate-node/pallets/pallet-tft-price/src/lib.rs, substrate-node/runtime/src/lib.rs
related to
-  https://github.com/threefoldtech/tfchain/issues/413
=> chore: upgrade substrate framework style

substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/tests.rs
=> test: create additional test for farming policies

substrate-node/pallets/pallet-tft-price/src/lib.rs, substrate-node/pallets/pallet-tft-price/src/tests.rs
=> feat: increase precision for average tft price

substrate-node/runtime/Cargo.toml, substrate-node/runtime/src/constants.rs
Improved the test. Still one concern. We should probably remove the tests from that file as they are testing the behavior from substrate which we expect to be correct.
=> feat: improve test full block fee is correct #465

substrate-node/Cargo.lock, substrate-node/pallets/pallet-tfgrid/Cargo.toml, substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/mock.rs, substrate-node/pallets/pallet-tfgrid/src/tests.rs
Council/root or allowed node certifiers can now modify node certification
=> feat: allow council to modify node certification

substrate-node/pallets/pallet-smart-contract/src/mock.rs, substrate-node/pallets/pallet-smart-contract/src/tests.rs
I forgot to modify the tests when implementing https://github.com/threefoldtech/tfchain/issues/485. I added them now.
=> feat: extend public ip test #488

substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/nodes_migration.rs, substrate-node/pallets/pallet-tfgrid/src/types.rs, substrate-node/runtime/src/lib.rs
to fix: https://github.com/threefoldtech/tfchain/issues/480
=> fix: migration for nodes by farm id storage

substrate-node/Cargo.lock, substrate-node/pallets/pallet-dao/src/tests.rs, substrate-node/pallets/pallet-validator/Cargo.toml, substrate-node/pallets/pallet-validator/src/lib.rs, substrate-node/pallets/pallet-validator/src/mock.rs, substrate-node/pallets/pallet-validator/src/tests.rs
related to:
- https://github.com/threefoldtech/tfchain/issues/455
=> test: add tests for pallet validator

substrate-node/pallets/pallet-dao/src/mock.rs, substrate-node/pallets/pallet-dao/src/tests.rs, substrate-node/pallets/pallet-smart-contract/src/mock.rs, substrate-node/pallets/pallet-smart-contract/src/tests.rs, substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/migrations/v12.rs, substrate-node/pallets/pallet-tfgrid/src/mock.rs, substrate-node/pallets/pallet-tfgrid/src/tests.rs, substrate-node/support/src/resources.rs, substrate-node/support/src/types.rs
=> fix: loosen tfgrid input validation

substrate-node/pallets/pallet-smart-contract/src/migrations/v7.rs
=> fix: migration v7 

substrate-node/pallets/pallet-tfgrid/src/terms_cond.rs
=> feat: terms and conditions URL validator (#519)

substrate-node/pallets/pallet-smart-contract/src/migrations/v6.rs, substrate-node/pallets/pallet-smart-contract/src/migrations/v7.rs, substrate-node/pallets/pallet-tfgrid/src/migrations/mod.rs, substrate-node/pallets/pallet-tfgrid/src/migrations/types.rs, substrate-node/pallets/pallet-tfgrid/src/migrations/v10.rs, substrate-node/pallets/pallet-tfgrid/src/migrations/v11.rs, substrate-node/pallets/pallet-tfgrid/src/migrations/v12.rs, substrate-node/pallets/pallet-tfgrid/src/migrations/v13.rs
Related to:
- #525
Should also solve:
- #526
=> fix: migration v12

substrate-node/pallets/pallet-smart-contract/src/lib.rs, substrate-node/pallets/pallet-smart-contract/src/migrations/v7.rs, substrate-node/pallets/pallet-smart-contract/src/mock.rs, substrate-node/pallets/pallet-smart-contract/src/tests.rs, substrate-node/pallets/pallet-smart-contract/src/types.rs, substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/support/src/types.rs, substrate-node/tests/TfChainClient.py
=> Fix #531 and implement #534

substrate-node/Cargo.lock, substrate-node/charts/substrate-node/Chart.yaml, substrate-node/charts/substrate-node/templates/deployment.yaml, substrate-node/charts/substrate-node/values.yaml, substrate-node/node/src/chain_spec.rs, substrate-node/pallets/pallet-smart-contract/src/mock.rs, substrate-node/pallets/pallet-smart-contract/src/tests.rs, substrate-node/pallets/pallet-tft-price/Cargo.toml, substrate-node/pallets/pallet-tft-price/src/lib.rs, substrate-node/pallets/pallet-tft-price/src/mock.rs, substrate-node/pallets/pallet-tft-price/src/tests.rs
This PR adds:
- Only allow Price to be set by a validator
- Offchain worker will now read out validator key and submit price with that key
=> feat: only allow block creators to set price

docs/development/create_account.md, docs/development/development.md, docs/development/rust-setup.md, docs/misc/adding_validators.md, docs/misc/create_farm.md, docs/misc/creating_validator.md, docs/misc/minimal_DAO.md
=> Fix: typos

substrate-node/Cargo.lock, substrate-node/node/Cargo.toml
This also removes some unused child dependencies.
Other changes in the Cargo.toml are some basic formatting done by editor on save.
=> Drop unused structopt dependency

docs/architecture/0007-twin-bond-stash-account.md, substrate-node/pallets/pallet-smart-contract/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/lib.rs, substrate-node/pallets/pallet-tfgrid/src/tests.rs, substrate-node/tests/integration_tests.robot
=> feat: allow twin to bond with a stash account

docs/architecture/0006-discount-levels-changed.md, docs/architecture/0008-discount-levels-changed.md, substrate-node/pallets/pallet-smart-contract/src/cost.rs, substrate-node/pallets/pallet-smart-contract/src/tests.rs
=> feat: lower discount level thresholds
