- substrate-node/charts/substrate-node/templates/deployment.yaml
By default, the command `key insert` uses sr25519 as a scheme to derive the public key. When inserting aura keys this is fine, but when we insert the grandpa key (ed25519) we need to explicity tell that it needs to be ed25519 encoded. To bad the official docs did not cover this :)
> fix keystore insertions

- pallets/pallet-tft-price/src/lib.rs
- pallets/pallet-tft-price/src/tests.rs
- substrate-node/node/src/chain_spec.rs
- substrate-node/runtime/src/lib.rs
Changes:
- Price set call is now only callable by the `AllowedOrigin`. This origin can be changed with the council or root. #246 
- Price set call is now free of charge #245
> feat(pallet-tft-price): refactor and improvements

- pallets/pallet-smart-contract/src/lib.rs
- pallets/pallet-smart-contract/src/tests.rs
This PR makes sure to `reserve` an amount of TFT when creating a RentContract. This makes sure that no exploit can happen by deploying a RentContract without costs on all of the nodes.
The reserved amount remains in reserved state until the user actually cancels the contract. If the contract is canceled, the reserved currency is freed and this amount is used as the last amount due by the user (last billing cycle)
> feat: add a lock to a part of the user funds when creating rent contract

- pallets/pallet-smart-contract/src/lib.rs
- pallets/pallet-smart-contract/src/tests.rs
- pallets/pallet-smart-contract/src/types.rs
Implements:
Switched reservedCurrency to lockableCurrency in order to couple a lock and a contract.
- Creating a RentContract now locks the amount due for 1 billing cycle, lock is released when RentContract is canceled
- Every contract object (nameContract, nodeContract, rentContract) now locks the amount due every billing cycle and distributes the amount locked every 24 hours (if the billing cycle is set to 1 hour)
- When any contract is canceled, the remained of that cycle is billed instead of the full cycle.
- Seconds elapsed in a billing cycle is now calculated based on the lock updated timestamp
> feat(pallet-smart-contract): bill every 24 hours instead of every billing cycle

- substrate-node/pallets/pallet-smart-contract/spec.md
- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/mock.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
- substrate-node/pallets/pallet-smart-contract/src/types.rs
- substrate-node/runtime/src/lib.rs
Implements a grace period state `GracePeriod(startBlockNumber)` for all contract types
A grace period is triggered if the amount due for a billing cycle is larger than the user's balance. A grace period is a static amount of time defined by the runtime configuration. A grace period is removed on a contract if the user reloads the balance on his account. If this happens, the contract is set back to `created` state. If a user ignores a graced out contract, the contract is deleted after the time defined by Grace Period configuration trait.
> feat: grace period for contracts

- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
When rent contract enters grace period, all associated node contracts are also set to grace period state in order for ZOS to pause these workloads. The reverse is done when the user adds funds to his wallet.
> fix: grace out node contracts if rent contract is graced out

- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/mock.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
- Does not move cancel contracts to grace period state if the user doesn't have enough balance
- Makes sure that only the amount available on the user's account get's billed
> fix: canceling contract can result in error #397

- substrate-node/pallets/pallet-tfgrid/src/grid_migration.rs
- substrate-node/pallets/pallet-tfgrid/src/lib.rs
- substrate-node/pallets/pallet-tfgrid/src/nodes_migration.rs
- substrate-node/pallets/pallet-tfgrid/src/tests.rs
- substrate-node/pallets/pallet-tfgrid/src/types.rs
- substrate-node/runtime/src/lib.rs
Adds a new storage map `NodesByFarmID`, double map with key being the farm id and the value being a list of node ids. Allows for easier lookup between a farm and it's nodes. #405 
`grid_migration` now put's the storage version to V7 and checks if it comes from V5 (compatible with all other networks)
`node_migration` also put's the storage version to V7 but checks if it came from V6
> feat: add farm / nodes index

- substrate-node/pallets/pallet-tfgrid/src/lib.rs
Also save certifcation level on 
- Farm
- Nodes (this way we don't have to manually toggle to them to certification level attached to the policy)
> chore: also save farm certification when policy is attached

- substrate-node/Cargo.lock
- substrate-node/pallets/pallet-dao/src/mock.rs
- substrate-node/pallets/pallet-dao/src/tests.rs
- substrate-node/pallets/pallet-smart-contract/src/mock.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
- substrate-node/pallets/pallet-tfgrid/Cargo.toml
- substrate-node/pallets/pallet-tfgrid/src/interface.rs
- substrate-node/pallets/pallet-tfgrid/src/lib.rs
- substrate-node/pallets/pallet-tfgrid/src/mock.rs
- substrate-node/pallets/pallet-tfgrid/src/pub_config.rs
- substrate-node/pallets/pallet-tfgrid/src/pub_ip.rs
- substrate-node/pallets/pallet-tfgrid/src/tests.rs
- substrate-node/pallets/pallet-tfgrid/src/types.rs
- substrate-node/runtime/src/lib.rs
Sadly, when using a type that has validation implemented it's not automaticaly checked when provided to an extrinsic. An input type is needed to convert from the input to the exact type where then validation occurs.
also use latest `valip` version
> fix: validation of node pub config/interfaces/ips

- substrate-node/pallets/pallet-tfgrid/src/grid_migration.rs
- substrate-node/pallets/pallet-tfgrid/src/lib.rs
- substrate-node/pallets/pallet-tfgrid/src/nodes_migration.rs
- substrate-node/pallets/pallet-tfgrid/src/nodes_migration_v2.rs
- substrate-node/pallets/pallet-tfgrid/src/types.rs
- substrate-node/runtime/src/lib.rs
Adds a new migration to redo the farm-node index. I checked on devnet fork, all went fine there.
This migration should not execute on other networks that's why I bumped to version in the gridmigration to v8
> fix: manage nodeByFarmID map when node is updated

- substrate-node/node/src/chain_spec.rs
- substrate-node/pallets/pallet-smart-contract/src/cost.rs
- substrate-node/pallets/pallet-smart-contract/src/mock.rs
- substrate-node/pallets/pallet-tft-price/src/lib.rs
- substrate-node/pallets/pallet-tft-price/src/mock.rs
- substrate-node/pallets/pallet-tft-price/src/tests.rs
Also adds a min tft price storage map. We can use this in smart contract layer to check if the avg price is lower, if so, use the min price
related to:
- #425 
- #423
> feat: allow setting bounds for avg tft price

- substrate-node/pallets/pallet-tfgrid/src/lib.rs
- substrate-node/pallets/pallet-tfgrid/src/tests.rs
When node is booted in other farm than initially booted in, the storage map of nodes by farm id should be properly updated.
> fix: update node

- substrate-node/support/src/resources.rs
PR https://github.com/threefoldtech/tfchain/pull/449 need to be reopened after a revert commit operation  https://github.com/threefoldtech/tfchain/commit/d883ca007dd58c45425e4eac17a7b655107ce2a5 due to new tfchain tag version https://github.com/threefoldtech/tfchain/commit/864ea673258360e22b79dc3acf9e3ece48e5ef27
> fix: adjust code to get rid of calc_cu() returns 0 case

- substrate-node/pallets/pallet-dao/src/lib.rs
- substrate-node/runtime/src/constants.rs
Both unit tests have been fixed. The reason for the failures:
**Failure 1**
assert_noop requires the state to be unchanged when there is a failure. The code was checking the input of the API call after changing the state. Thus it could modify the state before throwing an exception. 
**Failure 2**
I believe the calculation of the price for a full block is wrong. It should not be 16 dollars but instead 23.3112 dollars:
FEE_BLOCK = MAX_AMT_EXTRINSICS_PER_BLOCK * FEE_PER_EXTRINSIC
=> MAX_AMT_EXTRINSICS_PER_BLOCK = MAX_WEIGHT_PER_BLOCK/WEIGHT_PER_EXTRINSIC
=> MAX_AMT_EXTRINSICS_PER_BLOCK ≃ 23311.38
=> FEE_PER_EXTRINSIC = 1/10 cents
FEE_BLOCK ≃ 2331.138 cents = 23.31138 dollar
> feat: fixed both unit tests #457

- substrate-node/runtime/src/lib.rs
> fix: fetch authorities from validator pallet

- .github/workflows/build_test.yaml
- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/migration.rs
- substrate-node/pallets/pallet-smart-contract/src/mock.rs
- substrate-node/pallets/pallet-smart-contract/src/test_utils.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
- substrate-node/pallets/pallet-smart-contract/src/types.rs
- substrate-node/runtime/src/lib.rs
- substrate-node/tests/SubstrateNetwork.py
- substrate-node/tests/integration_tests.robot
Contracts will not get reinserted after a successful bill, rather it will get a index which can be calculated as following:
`Now block % billing frequency`
When a contract is created the index is generated as:
`Now block - 1 % billing frequency`
For such, the offchain worker will not bill the contract in the same block it gets created.
Even if the offchain worker now fails to bill the contract, it can be billed in the next cycle. The elapsed time between the first bill (or creation) and next bill is calculated anyway.
> feat: rework contract billing storage

- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
This PR fixes cases where contract grace period ends and distribution happens but fails because there are not enough funds on the user's wallet. This code now distributes as much as possible (what's left on the user's account).
https://github.com/threefoldtech/tfchain/issues/479
> fix: properly calculate rewards to be distributed in all cases

- substrate-node/pallets/pallet-smart-contract/src/cost.rs
- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/migrations/v7.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
- substrate-node/pallets/pallet-smart-contract/src/types.rs
- substrate-node/pallets/pallet-smart-contract/src/weights.rs
- substrate-node/tests/TfChainClient.py
- substrate-node/tests/integration_tests.robot
Removes deployment contract type since it was not really a "contract" object at all.
> feat: refactor deployment contract type

- substrate-node/Cargo.lock
- substrate-node/charts/substrate-node/Chart.yaml
- substrate-node/charts/substrate-node/templates/deployment.yaml
- substrate-node/charts/substrate-node/values.yaml
- substrate-node/pallets/pallet-smart-contract/Cargo.toml
- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/mock.rs
- substrate-node/tests/SubstrateNetwork.py
Currently, the author of a block is allowed to create the extrinsics to bill contracts. But these extrinsics are inserted into the next block. Because the author of these extrinsics won't get the transaction fee returned I choose an alternative path to only allow the next author to create the extrinsics and thus these extrinsics will be added in it's block and directly be refunded to it's account.
I also removed the need for `smct` key in the keystore. The reasoning is that we only run offchain workers on validators, since we already have the validator key in the keystore under `aura` keytype, there is no need to duplicate the key under `smct`.
A followup PR will also do the same for the Pricing pallet. This allows operations to setup validators a lot faster and worry less about different …
> fix: only allow next authority to create billing extrinsics

- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
> feat: improve service contract events

- cli-tool/cmds/farm_cmds/delete.js
- cli-tool/cmds/twin_cmds/delete.js
- cli-tool/src/farms.js
- cli-tool/src/twins.js
- substrate-node/pallets/pallet-smart-contract/src/lib.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
- substrate-node/pallets/pallet-tfgrid/spec.md
- substrate-node/pallets/pallet-tfgrid/src/lib.rs
- substrate-node/pallets/pallet-tfgrid/src/tests.rs
- substrate-node/tests/TfChainClient.py
- substrate-node/tests/integration_tests.robot
> feat: delete twin is not allowed

- substrate-node/Cargo.lock
- substrate-node/pallets/pallet-smart-contract/src/migrations/v7.rs
- substrate-node/pallets/pallet-tfgrid/src/node.rs
- substrate-node/pallets/pallet-tfgrid/src/tests.rs
- substrate-node/runtime/Cargo.toml
- substrate-node/runtime/src/lib.rs
- Removes min lenght from serial number validation
- Allows whitespaces
> fix: soften serial number validation

- substrate-node/pallets/pallet-smart-contract/src/cost.rs
- substrate-node/pallets/pallet-smart-contract/src/tests.rs
> fix: discount calculation handle variable billing frequency

- substrate-node/node/src/service.rs
related: https://github.com/threefoldtech/tfchain/issues/641
> fix: also configure compat mode on partial service
